#!/usr/bin/env ruby

require "bundler/setup"
require "ceol"

commands = ARGF.argv.first
Ceol::Controller.control do |controller|
  case commands
  when "off"
    controller.off
  when "on"
    controller.on
  when "digital"
    controller.digital_in
  when "analog"
    controller.analog_1
  when "mute"
    controller.mute
  when "unmute"
    controller.unmute
  else
    begin
      volume = Integer(commands, 10).clamp(0..60)
      controller.volume = volume
    rescue ArgumentError
      commands.each_char do |command|
        case command
        when "+"
          controller.volume_up
        when "-"
          controller.volume_down
        end
        sleep(0.5)
      end
    end
  end
end
