#!/usr/bin/env ruby

require "bundler/setup"
require "ceol"

commands = ARGF.argv.first
Ceol::Controller.control do |controller|
  case commands
  when "off"
    controller.off
  else
    commands.each_char do |command|
      case command
      when "+"
        controller.volume_up
      when "-"
        controller.volume_down
      end
      sleep(0.5)
    end
  end
end
